### ISSUE TITLE
Fails on Safari

### ISSUE THREAD

**Issue by aditiraveesh** [RiptideElements/pdfjs-build#1]
On Safari (version 7.1.7 and up), the pdf fails to open on a new tab. This fails silently without throwing any errors on console. Is there known issues with using this on Safari browser?

**Comment by DavidTPate** [comment]
@aditiraveesh We actually don't even use this anymore it's a pretty old build of `pdfjs`. I'd try out the latest version of `pdfjs` from Mozilla which is here: https://github.com/mozilla/pdfjs-dist and if you have an issue still, check out their issues & submit an issue there if you are still having an issue.

**Comment by aditiraveesh** [comment]
Alright, thank you. I'll check that out.
